import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { toast } from 'sonner';
import api from '../utils/api';
import { 
  Users, 
  IndianRupee, 
  TrendingUp, 
  FileText, 
  Search,
  Eye,
  Calendar,
  Briefcase,
  UserCheck,
  Loader2
} from 'lucide-react';

export default function EmployeeRevenueDashboard() {
  const [loading, setLoading] = useState(true);
  const [dashboardData, setDashboardData] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedEmployee, setSelectedEmployee] = useState(null);
  const [employeeBookings, setEmployeeBookings] = useState([]);
  const [loadingBookings, setLoadingBookings] = useState(false);
  const [showBookingsDialog, setShowBookingsDialog] = useState(false);
  const [dateFilter, setDateFilter] = useState({ start: '', end: '' });
  const [teamMembers, setTeamMembers] = useState([]);

  const user = JSON.parse(localStorage.getItem('user') || '{}');

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      const params = {};
      if (dateFilter.start) params.start_date = dateFilter.start;
      if (dateFilter.end) params.end_date = dateFilter.end;
      
      const response = await api.get('/employee-revenue', { params });
      setDashboardData(response.data);
    } catch (error) {
      console.error('Failed to fetch employee revenue data:', error);
      toast.error('Failed to load employee revenue data');
    } finally {
      setLoading(false);
    }
  };

  const fetchTeamMembers = async () => {
    try {
      const response = await api.get('/my-team');
      setTeamMembers(response.data.team_members || []);
    } catch (error) {
      console.error('Failed to fetch team members:', error);
    }
  };

  useEffect(() => {
    fetchDashboardData();
    fetchTeamMembers();
  }, []);

  const handleViewBookings = async (employee) => {
    setSelectedEmployee(employee);
    setLoadingBookings(true);
    setShowBookingsDialog(true);
    
    try {
      const params = {};
      if (dateFilter.start) params.start_date = dateFilter.start;
      if (dateFilter.end) params.end_date = dateFilter.end;
      
      const response = await api.get(`/employee-revenue/${employee.employee_id}/bookings`, { params });
      setEmployeeBookings(response.data.bookings || []);
    } catch (error) {
      console.error('Failed to fetch employee bookings:', error);
      toast.error('Failed to load bookings');
    } finally {
      setLoadingBookings(false);
    }
  };

  const filteredEmployees = dashboardData?.employee_details?.filter(emp => {
    const query = searchQuery.toLowerCase();
    return (
      emp.employee_name?.toLowerCase().includes(query) ||
      emp.employee_email?.toLowerCase().includes(query) ||
      emp.role_name?.toLowerCase().includes(query)
    );
  }) || [];

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(amount || 0);
  };

  const getRoleBadgeColor = (role) => {
    switch(role) {
      case 1: return 'bg-red-500';
      case 2: return 'bg-orange-500';
      case 3: return 'bg-purple-500';
      case 4: return 'bg-blue-500';
      case 5: return 'bg-green-500';
      default: return 'bg-gray-500';
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="p-4 md:p-6 lg:p-8 space-y-6" data-testid="employee-revenue-dashboard">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Employee Revenue Dashboard</h1>
          <p className="text-muted-foreground">Track revenue generated by team members</p>
        </div>
        <div className="flex items-center gap-2">
          <Input
            type="date"
            value={dateFilter.start}
            onChange={(e) => setDateFilter(prev => ({ ...prev, start: e.target.value }))}
            className="w-40"
          />
          <span className="text-muted-foreground">to</span>
          <Input
            type="date"
            value={dateFilter.end}
            onChange={(e) => setDateFilter(prev => ({ ...prev, end: e.target.value }))}
            className="w-40"
          />
          <Button onClick={fetchDashboardData} variant="outline">
            <Calendar className="h-4 w-4 mr-2" />
            Apply
          </Button>
        </div>
      </div>

      {/* Current User Info */}
      <Card className="bg-gradient-to-r from-emerald-50 to-teal-50 dark:from-emerald-950 dark:to-teal-900 border-emerald-200 dark:border-emerald-800">
        <CardContent className="p-4">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white font-bold text-lg">
              {user.name?.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)}
            </div>
            <div>
              <p className="font-semibold text-lg">{user.name}</p>
              <p className="text-sm text-muted-foreground">{user.role_name} • {user.email}</p>
            </div>
            {teamMembers.length > 0 && (
              <div className="ml-auto text-right">
                <p className="text-sm text-muted-foreground">Team Size</p>
                <p className="text-2xl font-bold text-emerald-600">{teamMembers.length}</p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-950 dark:to-blue-900 border-blue-200 dark:border-blue-800">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-blue-600 dark:text-blue-400">Team Members</p>
                <p className="text-3xl font-bold text-blue-900 dark:text-blue-100">{dashboardData?.total_employees || 0}</p>
              </div>
              <Users className="h-10 w-10 text-blue-500" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-green-50 to-green-100 dark:from-green-950 dark:to-green-900 border-green-200 dark:border-green-800">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-green-600 dark:text-green-400">Total Revenue</p>
                <p className="text-2xl font-bold text-green-900 dark:text-green-100">{formatCurrency(dashboardData?.total_revenue)}</p>
              </div>
              <IndianRupee className="h-10 w-10 text-green-500" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-purple-50 to-purple-100 dark:from-purple-950 dark:to-purple-900 border-purple-200 dark:border-purple-800">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-purple-600 dark:text-purple-400">Total Commission</p>
                <p className="text-2xl font-bold text-purple-900 dark:text-purple-100">{formatCurrency(dashboardData?.total_commission)}</p>
              </div>
              <TrendingUp className="h-10 w-10 text-purple-500" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-orange-50 to-orange-100 dark:from-orange-950 dark:to-orange-900 border-orange-200 dark:border-orange-800">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-orange-600 dark:text-orange-400">Total Bookings</p>
                <p className="text-3xl font-bold text-orange-900 dark:text-orange-100">{dashboardData?.total_bookings || 0}</p>
              </div>
              <FileText className="h-10 w-10 text-orange-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search */}
      <div className="flex items-center gap-2">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search by name, email, or role..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10"
          />
        </div>
      </div>

      {/* Employee List */}
      <Card>
        <CardHeader>
          <CardTitle>Team Performance</CardTitle>
          <CardDescription>Revenue breakdown by team member</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Employee</TableHead>
                  <TableHead>Role</TableHead>
                  <TableHead className="text-right">Clients</TableHead>
                  <TableHead className="text-right">Bookings</TableHead>
                  <TableHead className="text-right">Revenue</TableHead>
                  <TableHead className="text-right">Commission</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredEmployees.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className="text-center py-8 text-muted-foreground">
                      No team members found
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredEmployees.map((emp) => (
                    <TableRow key={emp.employee_id} className={emp.employee_id === user.id ? 'bg-emerald-50 dark:bg-emerald-950/30' : ''}>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold ${getRoleBadgeColor(emp.role)}`}>
                            {emp.employee_name?.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)}
                          </div>
                          <div>
                            <p className="font-medium">{emp.employee_name}</p>
                            <p className="text-xs text-muted-foreground">{emp.employee_email}</p>
                          </div>
                          {emp.employee_id === user.id && (
                            <Badge variant="outline" className="text-xs">You</Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge className={getRoleBadgeColor(emp.role)}>
                          {emp.role_name}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">{emp.total_clients}</TableCell>
                      <TableCell className="text-right">{emp.total_bookings}</TableCell>
                      <TableCell className="text-right font-medium text-green-600 dark:text-green-400">
                        {formatCurrency(emp.total_revenue)}
                      </TableCell>
                      <TableCell className="text-right font-medium text-purple-600 dark:text-purple-400">
                        {formatCurrency(emp.total_commission)}
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-1">
                          {emp.completed_bookings > 0 && (
                            <Badge variant="default" className="bg-green-500">
                              {emp.completed_bookings} Done
                            </Badge>
                          )}
                          {emp.pending_bookings > 0 && (
                            <Badge variant="secondary">
                              {emp.pending_bookings} Pending
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleViewBookings(emp)}
                          disabled={emp.total_bookings === 0}
                        >
                          <Eye className="h-4 w-4 mr-1" />
                          View
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* Bookings Dialog */}
      <Dialog open={showBookingsDialog} onOpenChange={setShowBookingsDialog}>
        <DialogContent className="sm:max-w-4xl">
          <DialogHeader>
            <DialogTitle>
              Bookings for {selectedEmployee?.employee_name} ({selectedEmployee?.role_name})
            </DialogTitle>
          </DialogHeader>
          
          {loadingBookings ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Booking #</TableHead>
                  <TableHead>Client</TableHead>
                  <TableHead>Stock</TableHead>
                  <TableHead className="text-right">Qty</TableHead>
                  <TableHead className="text-right">Value</TableHead>
                  <TableHead className="text-right">Commission</TableHead>
                  <TableHead>RP</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Date</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {employeeBookings.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={9} className="text-center py-8 text-muted-foreground">
                      No bookings found
                    </TableCell>
                  </TableRow>
                ) : (
                  employeeBookings.map((booking, idx) => (
                    <TableRow key={idx}>
                      <TableCell className="font-mono text-sm">{booking.booking_number}</TableCell>
                      <TableCell>{booking.client_name}</TableCell>
                      <TableCell>{booking.stock_symbol}</TableCell>
                      <TableCell className="text-right">{booking.quantity}</TableCell>
                      <TableCell className="text-right">{formatCurrency(booking.total_value)}</TableCell>
                      <TableCell className="text-right text-purple-600">{formatCurrency(booking.employee_commission_amount)}</TableCell>
                      <TableCell>{booking.rp_name || '-'}</TableCell>
                      <TableCell>
                        <Badge variant={booking.status === 'Completed' ? 'default' : 'secondary'}>
                          {booking.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {new Date(booking.created_at).toLocaleDateString()}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
