/**
 * Login Page Constants
 * Contains all quotes, keywords, and themes for the login page
 */
import {
  DollarSign, Key, Briefcase, Target, Gem, Timer, TrendingUp, Crown, Coins,
  Banknote, Scale, Shield, Rocket, Users, Layers, Globe, Award, PieChart,
  Landmark, Sparkles, Search, BarChart3, LineChart, Compass, Zap, Brain,
  Activity, Maximize, Droplet, Anchor, Wallet, Folder, FileText, ShoppingCart,
  Calculator, ClipboardList, FileSearch, Hash, Percent, Plug, Leaf, Package, Star
} from 'lucide-react';

// All 69 SMIFS PE Quotes
export const PE_QUOTES = [
  "Private equity is the art of patient capital.",
  "Public markets rent shares; private equity buys ownership.",
  "We don't buy tickers; we buy businesses.",
  "Liquidity is a luxury; illiquidity is a strategy.",
  "In private markets, time is a tool, not a constraint.",
  "Volatility is the price of liquidity; stability is the reward of the lock-in.",
  "True value is created in the dark, away from the daily ticker.",
  "Private equity doesn't predict the future; it engineers it.",
  "You cannot fix a company while checking its stock price every minute.",
  "Public markets react; private markets act.",
  "The illiquidity premium is the payment for patience.",
  "Alpha is found where the spotlight isn't shining.",
  "Efficient markets are for saving; inefficient markets are for earning.",
  "Wealth is built in private; it is merely revealed in public.",
  "Price is what you pay; structure is how you protect it.",
  "You make your profit on the buy, you realize it on the sell.",
  "Valuation is an opinion; cash flow is a fact.",
  "Don't catch falling knives; buy the floor.",
  "A great company at a bad price is a bad investment.",
  "Due diligence is the art of asking the question nobody wants to answer.",
  "Growth covers mistakes; leverage magnifies them.",
  "Buy the complexity, sell the simplicity.",
  "The best deals are often the hardest to close.",
  "Cynicism protects capital; optimism grows it.",
  "Entry multiple is destiny.",
  "Leverage is a good servant but a terrible master.",
  "Never fall in love with the deal; fall in love with the economics.",
  "Risk comes from not knowing what you are doing.",
  "In PE, 'cheap' is expensive if it can't be fixed.",
  "Bet on the jockey, not just the horse.",
  "Financial engineering is a tactic; operational improvement is a strategy.",
  "Alignment of interest is the most powerful force in finance.",
  "Skin in the game changes the game.",
  "A spreadsheet cannot manage a workforce.",
  "Change is hard in public; it is essential in private.",
  "Hope is not a strategy; execution is.",
  "EBITDA is an opinion; Free Cash Flow is reality.",
  "Transformation requires a runway, not a tightrope.",
  "Strong boards don't just monitor; they mentor.",
  "Cost cutting buys you time; revenue growth buys you a future.",
  "Culture eats strategy for breakfast, even in a leveraged buyout.",
  "Turnarounds don't happen in a straight line.",
  "The goal is not to be bigger; the goal is to be better.",
  "Incentives dictate behavior; get the cap table right.",
  "If you aren't growing, you're dying—slowly.",
  "Scale breaks systems; fix the system before you scale.",
  "M&A is like marriage: easy to get into, expensive to get out of.",
  "Synergies are easy to model but hard to capture.",
  "Bolt-ons are the unsung heroes of multiple expansion.",
  "Organic growth proves the concept; inorganic growth proves the platform.",
  "Focus on the core; outsource the noise.",
  "Revenue is vanity, profit is sanity, cash is king.",
  "A platform is worth more than the sum of its parts.",
  "Don't just capture market share; create market value.",
  "Every entry must have an exit strategy.",
  "You don't sell when you want to; you sell when the market wants to buy.",
  "IPOs are a branding event; strategic sales are a synergy event.",
  "Multiple expansion is luck; earnings growth is skill.",
  "The J-Curve is steep, but the view from the top is worth it.",
  "Leaving money on the table is better than holding the bag.",
  "An exit is not the end; it's the validation of the thesis.",
  "Returns are realized in cash, not in mark-to-market reports.",
  "Don't wait for the perfect exit; look for the good one.",
  "A great exit makes you forget the hard years.",
  "Capital goes where it is welcome and stays where it is well treated.",
  "Reputation takes twenty years to build and five minutes to ruin.",
  "In the long run, the fundamentals always win.",
  "Private Equity: Fueling the real economy.",
  "We don't just manage wealth; we steward potential.",
];

// Floating icon keywords with their icons
export const FLOATING_KEYWORDS = [
  { word: "CAPITAL", icon: DollarSign },
  { word: "OWNERSHIP", icon: Key },
  { word: "BUSINESS", icon: Briefcase },
  { word: "STRATEGY", icon: Target },
  { word: "VALUE", icon: Gem },
  { word: "PATIENCE", icon: Timer },
  { word: "GROWTH", icon: TrendingUp },
  { word: "ALPHA", icon: Crown },
  { word: "WEALTH", icon: Coins },
  { word: "CASH FLOW", icon: Banknote },
  { word: "LEVERAGE", icon: Scale },
  { word: "RISK", icon: Shield },
  { word: "EXECUTION", icon: Rocket },
  { word: "CULTURE", icon: Users },
  { word: "SYNERGY", icon: Layers },
  { word: "PLATFORM", icon: Globe },
  { word: "EXIT", icon: Award },
  { word: "RETURNS", icon: PieChart },
  { word: "FUNDAMENTALS", icon: Landmark },
  { word: "POTENTIAL", icon: Sparkles },
  { word: "DILIGENCE", icon: Search },
  { word: "ECONOMICS", icon: BarChart3 },
  { word: "PROFIT", icon: LineChart },
  { word: "ALIGNMENT", icon: Compass },
  { word: "TRANSFORM", icon: Zap },
  { word: "MENTOR", icon: Brain },
  { word: "REVENUE", icon: Activity },
  { word: "SCALE", icon: Maximize },
  { word: "M&A", icon: Layers },
  { word: "MARKET", icon: Globe },
  { word: "LIQUIDITY", icon: Droplet },
  { word: "STABILITY", icon: Anchor },
  { word: "VOLATILITY", icon: Activity },
  { word: "EQUITY", icon: PieChart },
  { word: "INVESTMENT", icon: Wallet },
  { word: "PORTFOLIO", icon: Folder },
  { word: "THESIS", icon: FileText },
  { word: "BUYOUT", icon: ShoppingCart },
  { word: "IPO", icon: Rocket },
  { word: "EARNINGS", icon: Calculator },
  { word: "J-CURVE", icon: LineChart },
  { word: "CAP TABLE", icon: ClipboardList },
  { word: "DUE DILIG", icon: FileSearch },
  { word: "EBITDA", icon: Hash },
  { word: "MULTIPLE", icon: Percent },
  { word: "BOLT-ON", icon: Plug },
  { word: "ORGANIC", icon: Leaf },
  { word: "INORGANIC", icon: Package },
  { word: "BOARD", icon: Users },
  { word: "STEWARD", icon: Star },
];

// Theme configurations
export const LOGIN_THEMES = [
  { primary: 'emerald', secondary: 'teal', accent: 'green', gradient: 'from-slate-950 via-emerald-950 to-slate-900' },
  { primary: 'cyan', secondary: 'blue', accent: 'sky', gradient: 'from-slate-950 via-cyan-950 to-slate-900' },
  { primary: 'violet', secondary: 'purple', accent: 'fuchsia', gradient: 'from-slate-950 via-violet-950 to-slate-900' },
  { primary: 'amber', secondary: 'orange', accent: 'yellow', gradient: 'from-slate-950 via-amber-950 to-slate-900' },
  { primary: 'rose', secondary: 'pink', accent: 'red', gradient: 'from-slate-950 via-rose-950 to-slate-900' },
  { primary: 'emerald', secondary: 'lime', accent: 'green', gradient: 'from-gray-950 via-emerald-950 to-gray-900' },
];

// Get random theme
export const getRandomTheme = () => LOGIN_THEMES[Math.floor(Math.random() * LOGIN_THEMES.length)];

// Logo URL
export const LOGO_URL = "https://customer-assets.emergentagent.com/job_8c5c41a7-4474-44d9-8a72-5476f60329b4/artifacts/eineo77y_SMIFS%20%26%20PRIVITY%20Logo.png";
